[package]
name = "day6"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
regex = "*"
colored = "1.6"
log = {version = "*", features=["release_max_level_info"]}
env_logger = "*"
num = "*"
num-traits = "*"