[package]
name = "day7"
version = "0.1.0"
authors = ["Omer Ben-Amram <omerbenamram@gmail.com>"]
edition = "2018"

[dependencies]
petgraph = "*"
regex = "*"
lazy_static = "*"
failure = "*"
log = {version = "*", features=["release_max_level_info"]}
env_logger = "*"
colored = "1.6.1"